### ISSUE TITLE
ERROR in src/app/app.module.ts:28:38

### ISSUE THREAD

**Issue by elzasimoes** [cod3rcursos/angular-crud#1]
> ERROR in src/app/app.module.ts:28:38 - error TS2307: Cannot find module './components/product/product-read/product-read.component'

![image](https://user-images.githubusercontent.com/12284488/80837650-3c9d9580-8bc5-11ea-944b-d324d96a8edd.png)

Ocorreu depois que importei o <app-product-read> no `product-crud.component.html`

Já tentei de tudo e nada...

**Comment by elzasimoes** [comment]
Dei um restart no servidor e funcionou, desconsiderar.

**Comment by wfrsilva** [comment]
Não sei se ajuda, mas se quiser comparar:
https://github.com/wfrsilva/AngularJson01_COD3R
